#!/usr/bin/bash

TEMPLATEDIR=./template/
VERSION=0
RELEASE=0
TARGET="-bs"

# parse command line options
for i in "$@"; do
  case $i in
    --help)
    OPTS_HELP=YES
    shift # past argument
    ;;
    --version=*)
    VERSION="${i#*=}"
    shift # past argument
    ;;
    --release=*)
    RELEASE="${i#*=}"
    shift # past argument
    ;;
    --build)
    TARGET="-ba"
    shift # past argument
    ;;
    *)
          # unknown option
    ;;
  esac
done

if [ -n "$OPTS_HELP" ]; then
  man create-fake-rpm | cat
  exit 0;
fi

NAME=$1
PROVIDES=$2

rpmbuild --define="fake_name $NAME" --define="fake_provides $PROVIDES" \
        --define="fake_version $VERSION" --define="fake_release $RELEASE" \
        --define "_sourcedir $PWD" \
        --define "_rpmdir $PWD" \
        --define "_specdir $PWD" \
        --define "_builddir $PWD" \
        --define "_srcrpmdir $PWD" \
        "$TARGET" "$TEMPLATEDIR/template.spec"


